version: '3.6'
services:
  pixel_battle_back:
    container_name: pixel_battle_back
    restart: always
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
      CONFIG_SERVER_URL: http://config_server
      SERVICE_NAME: pixel-battle-back
      NAMESPACE: prod
      M_TOKEN: ${M_TOKEN}
networks:
  dc-net:
    external: true