version: '3.6'
services:
  pixel_battle_back:
    container_name: pixel_battle_back
    restart: always
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
      DB_HOST: ${DB_HOST-localhost}
      DB_LOGIN: ${DB_USER-root}
      DB_PASS: ${MYSQL_ROOT_PASSWORD-1234}
      DB_NAME: pixel_battle
      CONTAINER_PORT: ${CONFIG_SERVER_CONTAINER_PORT-80}
      OUTER_PORT: ${OUTER_PORT-80}
      LOGOTIPIWE_GMAIL_ID: ${LOGOTIPIWE_GMAIL_ID}
      G_OAUTH_CLIENT_SECRET: ${G_OAUTH_CLIENT_SECRET}
      SUBPATH: /pixel-battle-back
      OUTER_SCHEME : ${OUTER_SCHEME}
      OUTER_HOST : ${OUTER_HOST}
networks:
  dc-net:
    external: true