version: '3.6'
services:
  pixel_battle_back:
    container_name: pixel_battle_back
    restart: always
    build: .
    networks:
      - dc-net
    environment:
      CONFIG_SERVER_URL: http://config_server
      SERVICE_NAME: pixel-battle-back
      NAMESPACE: dev-dc
      M_TOKEN: ${M_TOKEN}
    ports:
      - 82:80
networks:
  dc-net:
    external: true