name: Pixel battle back CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: Logotipiwe/dc_vars
        token: ${{secrets.PAT}}
    - name: load-env
      uses: duskmoon314/action-load-env@v1.1.0

    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PAT }}
    - name: Build
      id: build_push
      run: |
        ls
        export APP_NAME=pixel_battle_back
        export IMAGE=${{ env.DOCKER_USER }}/${APP_NAME}:$(date +%s)
        docker build . -t ${IMAGE}
        docker push ${IMAGE}
        echo "APP_NAME=${APP_NAME}" >> "$GITHUB_ENV"
        echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"
    - name: Upload
      uses: garygrossgarten/github-action-scp@release
      with:
        local: .
        concurrency: 20
        remote: /kuber/pixel_battle_back
        host: ${{ env.DC_HOST }}
        username: ${{ env.SSH_USER }}
        password: ${{ env.SSH_PASSWORD }}
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ env.DC_HOST }}
        username: ${{ env.SSH_USER }}
        password: ${{ env.SSH_PASSWORD }}
        port: 22
        script: |
          export IMAGE=${{ env.IMAGE }}
          export LOGOTIPIWE_GMAIL_ID=${{ env.LOGOTIPIWE_GMAIL_ID }}
          export G_OAUTH_CLIENT_SECRET=${{ env.G_OAUTH_CLIENT_SECRET }}
          export OUTER_SCHEME=${{ env.OUTER_SCHEME }}
          export OUTER_HOST=${{ env.OUTER_HOST }}
          export DB_HOST=${{ env.DB_HOST }}
          export DB_LOGIN=${{ env.DB_USER }}
          export DB_PASS=${{ env.MYSQL_ROOT_PASSWORD }}
          docker-compose -f /kuber/${{ env.APP_NAME }}/${{ env.APP_NAME }}.yml down --remove-orphans
          docker-compose -f /kuber/${{ env.APP_NAME }}/${{ env.APP_NAME }}.yml up -d
